# Streamlit secrets configuration
# This file is used when the app is deployed to Streamlit Cloud
# Add your actual values here (keep this file secure and don't commit to version control)

WHOOP_CLIENT_ID = "your_whoop_client_id_here"
WHOOP_CLIENT_SECRET = "your_whoop_client_secret_here"
WHOOP_REDIRECT_URI = "https://your-app-name.streamlit.app"
